export const fallbackNowPlayingMovies = [
  {
    adult: false,
    backdrop_path: "/kqHypb4MdEBUFiphf49bK99T4cn.jpg",
    genre_ids: [878, 53],
    id: 755898,
    original_language: "en",
    original_title: "War of the Worlds",
    overview:
      "Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.",
    popularity: 1820.7774,
    poster_path: "/yvirUYrva23IudARHn3mMGVxWqM.jpg",
    release_date: "2025-07-29",
    title: "War of the Worlds",
    video: false,
    vote_average: 4.4,
    vote_count: 257,
  },
  {
    adult: false,
    backdrop_path: "/fncHijpWjitFBmj7SX5z148XEhP.jpg",
    genre_ids: [878, 12, 28],
    id: 1234821,
    original_language: "en",
    original_title: "Jurassic World Rebirth",
    overview:
      "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
    popularity: 1127.7172,
    poster_path: "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
    release_date: "2025-07-01",
    title: "Jurassic World Rebirth",
    video: false,
    vote_average: 6.399,
    vote_count: 1365,
  },
  {
    adult: false,
    backdrop_path: "/y7tjLYcq2ZGy2DNG0ODhGX9Tm60.jpg",
    genre_ids: [28, 35, 80],
    id: 1106289,
    original_language: "en",
    original_title: "The Pickup",
    overview:
      "A routine cash pickup takes a wild turn when mismatched armored truck drivers Russell and Travis are ambushed by ruthless criminals led by savvy mastermind Zoe.",
    popularity: 517.1636,
    poster_path: "/vFWvWhfAvij8UIngg2Vf6JV95Cr.jpg",
    release_date: "2025-07-27",
    title: "The Pickup",
    video: false,
    vote_average: 6.626,
    vote_count: 170,
  },
  {
    adult: false,
    backdrop_path: "/iZztGzckOMByRRQgsFh2yk3udkU.jpg",
    genre_ids: [28, 27, 10749],
    id: 986206,
    original_language: "en",
    original_title: "Night Carnage",
    overview:
      "A blogger who is also a werewolf meets a dashing playboy with a dark secret of his own. Starring Logan Andrews and Christian Howard.",
    popularity: 327.6566,
    poster_path: "/w0wjPQKhlqisSbylf1sWZiNyc2h.jpg",
    release_date: "2025-07-29",
    title: "Night Carnage",
    video: false,
    vote_average: 5.73,
    vote_count: 37,
  },
  {
    adult: false,
    backdrop_path: "/bP6BqIljp4a3BqhxN7YPckcpKI.jpg",
    genre_ids: [28, 18, 36],
    id: 1195631,
    original_language: "en",
    original_title: "William Tell",
    overview:
      "The narrative unfolds in the 14th Century, when the European nations vie for supremacy within the Holy Roman Empire. The ambitious Austrian Empire, desiring more land, invades neighbouring Switzerland, a serene and pastoral nation. Protagonist William Tell, a formerly peaceful hunter, finds himself forced to take action as his family and homeland come under threat from the oppressive Austrian King and his ruthless warlords.",
    popularity: 468.2674,
    poster_path: "/8SdaetXSTPyQVDb5pTEPRLBSx15.jpg",
    release_date: "2025-01-17",
    title: "William Tell",
    video: false,
    vote_average: 6.283,
    vote_count: 83,
  },
  {
    adult: false,
    backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
    genre_ids: [16, 28, 14, 53],
    id: 1311031,
    original_language: "ja",
    original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
    overview:
      "As the Demon Slayer Corps members and Hashira engaged in a group strength training program, the Hashira Training, in preparation for the forthcoming battle against the demons, Muzan Kibutsuji appears at the Ubuyashiki Mansion. With the head of the Demon Corps in danger, Tanjiro and the Hashira rush to the headquarters but are plunged into a deep descent to a mysterious space by the hands of Muzan Kibutsuji.  The destination of where Tanjiro and Demon Slayer Corps have fallen is the demons' stronghold – the Infinity Castle. And so, the battleground is set as the final battle between the Demon Slayer Corps and the demons ignites.",
    popularity: 352.5289,
    poster_path: "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
    release_date: "2025-07-18",
    title: "Demon Slayer: Kimetsu no Yaiba — Infinity Castle",
    video: false,
    vote_average: 7.1,
    vote_count: 68,
  },
  {
    adult: false,
    backdrop_path: "/7A3ru3bxmWtyF0ep0CJcLLzWT35.jpg",
    genre_ids: [28, 18, 36],
    id: 1185528,
    original_language: "zh",
    original_title: "射雕英雄传：侠之大者",
    overview:
      "Under Genghis Khan, the Mongolian army pushes west to destroy the Jin Dynasty, setting its sights on the Song Dynasty next. Amid internal conflicts among martial arts schools, Guo Jing unites the Central Plains' warriors to defend Xiangyang, embodying courage and loyalty in the fight for the nation.",
    popularity: 388.8982,
    poster_path: "/fUCFEGFlMIFet9ja72JDAeG1he8.jpg",
    release_date: "2025-01-29",
    title: "Legends of the Condor Heroes: The Gallants",
    video: false,
    vote_average: 6.152,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: "/zav0v7gLWMu6pVwgsIAwt11GJ4C.jpg",
    genre_ids: [27, 53, 878],
    id: 1100988,
    original_language: "en",
    original_title: "28 Years Later",
    overview:
      "Twenty-eight years since the rage virus escaped a biological weapons laboratory, now, still in a ruthlessly enforced quarantine, some have found ways to exist amidst the infected. One such group lives on a small island connected to the mainland by a single, heavily-defended causeway. When one member departs on a mission into the dark heart of the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors as well.",
    popularity: 254.6574,
    poster_path: "/mIg1qCkVxnAlM2TK3RUF0tdEXlE.jpg",
    release_date: "2025-06-18",
    title: "28 Years Later",
    video: false,
    vote_average: 6.869,
    vote_count: 1045,
  },
  {
    adult: false,
    backdrop_path: "/A466i5iATrpbVjX30clP1Zyfp31.jpg",
    genre_ids: [10749, 35, 18],
    id: 1307078,
    original_language: "en",
    original_title: "My Oxford Year",
    overview:
      "An ambitious American fulfilling her dream of studying at Oxford falls for a charming Brit hiding a secret that may upend her perfectly planned life.",
    popularity: 236.4227,
    poster_path: "/jrhXbIOFingzdLjkccjg9vZnqIp.jpg",
    release_date: "2025-07-31",
    title: "My Oxford Year",
    video: false,
    vote_average: 7.249,
    vote_count: 207,
  },
  {
    adult: false,
    backdrop_path: "/cEQMqB3ahd4mfeUN6VGC0ouVnZZ.jpg",
    genre_ids: [28, 878, 53],
    id: 1071585,
    original_language: "en",
    original_title: "M3GAN 2.0",
    overview:
      "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
    popularity: 240.5492,
    poster_path: "/4a63rQqIDTrYNdcnTXdPsQyxVLo.jpg",
    release_date: "2025-06-25",
    title: "M3GAN 2.0",
    video: false,
    vote_average: 7.611,
    vote_count: 659,
  },
  {
    adult: false,
    backdrop_path: "/kyqM6padQzZ1eYxv84i9smNvZAG.jpg",
    genre_ids: [27, 9648],
    id: 1078605,
    original_language: "en",
    original_title: "Weapons",
    overview:
      "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
    popularity: 249.1853,
    poster_path: "/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg",
    release_date: "2025-08-06",
    title: "Weapons",
    video: false,
    vote_average: 7.711,
    vote_count: 197,
  },
  {
    adult: false,
    backdrop_path: "/eU7IfdWq8KQy0oNd4kKXS0QUR08.jpg",
    genre_ids: [878, 12, 28],
    id: 1061474,
    original_language: "en",
    original_title: "Superman",
    overview:
      "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
    popularity: 199.5313,
    poster_path: "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
    release_date: "2025-07-09",
    title: "Superman",
    video: false,
    vote_average: 7.68,
    vote_count: 1635,
  },
  {
    adult: false,
    backdrop_path: "/s94NjfKkcSczZ1FembwmQZwsuwY.jpg",
    genre_ids: [878, 12],
    id: 617126,
    original_language: "en",
    original_title: "The Fantastic 4: First Steps",
    overview:
      "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
    popularity: 192.4302,
    poster_path: "/x26MtUlwtWD26d0G0FXcppxCJio.jpg",
    release_date: "2025-07-23",
    title: "The Fantastic 4: First Steps",
    video: false,
    vote_average: 7.264,
    vote_count: 912,
  },
  {
    adult: false,
    backdrop_path: "/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg",
    genre_ids: [28, 12, 18],
    id: 1011477,
    original_language: "en",
    original_title: "Karate Kid: Legends",
    overview:
      "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
    popularity: 195.2787,
    poster_path: "/AEgggzRr1vZCLY86MAp93li43z.jpg",
    release_date: "2025-05-08",
    title: "Karate Kid: Legends",
    video: false,
    vote_average: 7.162,
    vote_count: 634,
  },
  {
    adult: false,
    backdrop_path: "/x5dVPttNDZaVRTvbk7pYrtGZoZN.jpg",
    genre_ids: [35, 18],
    id: 1263256,
    original_language: "en",
    original_title: "Happy Gilmore 2",
    overview:
      "Happy Gilmore isn't done with golf — not by a long shot. Since his retirement after his first Tour Championship win, Gilmore returns to finance his daughter's ballet classes.",
    popularity: 163.5284,
    poster_path: "/ynT06XivgBDkg7AtbDbX1dJeBGY.jpg",
    release_date: "2025-07-25",
    title: "Happy Gilmore 2",
    video: false,
    vote_average: 6.764,
    vote_count: 518,
  },
  {
    adult: false,
    backdrop_path: "/1KwliRKTw61fRGmbG4Sf8eWOHP.jpg",
    genre_ids: [28, 35, 80],
    id: 1181540,
    original_language: "en",
    original_title: "Guns Up",
    overview:
      "When a job goes horribly wrong, an ex-cop and family man who moonlights as a mob henchman has one night to get his family out of the city.",
    popularity: 142.7029,
    poster_path: "/3RokBWEkQqJRZEVP3DPwGm5MYh6.jpg",
    release_date: "2025-05-15",
    title: "Guns Up",
    video: false,
    vote_average: 6.849,
    vote_count: 63,
  },
  {
    adult: false,
    backdrop_path: "/r2u7GCYhxtpZbprKJIgdAkGQow3.jpg",
    genre_ids: [27, 35],
    id: 1225572,
    original_language: "en",
    original_title: "Screamboat",
    overview:
      "A late-night boat ride turns into a desperate fight for survival in New York City when a mischievous mouse becomes a monstrous reality.",
    popularity: 188.2499,
    poster_path: "/78xGAhQaKpgq9TI08XK40Ua2bGx.jpg",
    release_date: "2025-03-20",
    title: "Screamboat",
    video: false,
    vote_average: 4.84,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: "/oPgXVSdGR9dGwbmvIToOCMmsdc2.jpg",
    genre_ids: [28, 53, 80],
    id: 541671,
    original_language: "en",
    original_title: "Ballerina",
    overview:
      "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
    popularity: 158.5197,
    poster_path: "/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
    release_date: "2025-06-04",
    title: "Ballerina",
    video: false,
    vote_average: 7.439,
    vote_count: 1293,
  },
  {
    adult: false,
    backdrop_path: "/b0yK9BHyTNHGS6fBFLXBFtLC9AW.jpg",
    genre_ids: [27],
    id: 1452176,
    original_language: "en",
    original_title: "Abraham's Boys: A Dracula Story",
    overview:
      "Following the events of Dracula, Abraham van Helsing moves his two sons, Max and Rudy, to the US in an attempt to escape their past. It does not work.",
    popularity: 157.9263,
    poster_path: "/e10AbPwcJk5b7ja3MQUVr5wHEeq.jpg",
    release_date: "2025-07-11",
    title: "Abraham's Boys: A Dracula Story",
    video: false,
    vote_average: 4.6,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: "/2DcD4Hh80SW7YVpwckkiEFRZX06.jpg",
    genre_ids: [28, 35],
    id: 1124619,
    original_language: "en",
    original_title: "Bride Hard",
    overview:
      "Sam is a secret agent whose toughest mission to date is pleasing her bride-to-be best friend at a lavish destination wedding. When a team of mercenaries crashes the party and takes the guests hostage, Sam is thrown into a fight unlike any before — one where she can’t risk blowing her cover or ruining the big day. As she takes on the bad guys in a high-stakes battle disguised as a fairy-tale affair, she realizes the real threat might be closer than she thinks.",
    popularity: 130.5087,
    poster_path: "/3mExdWLSxAiUCb4NMcYmxSkO7n4.jpg",
    release_date: "2025-06-19",
    title: "Bride Hard",
    video: false,
    vote_average: 5.746,
    vote_count: 69,
  },
];

export const fallbackPopularMovies = [
  {
    adult: false,
    backdrop_path: "/kqHypb4MdEBUFiphf49bK99T4cn.jpg",
    genre_ids: [878, 53],
    id: 755898,
    original_language: "en",
    original_title: "War of the Worlds",
    overview:
      "Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.",
    popularity: 1820.7774,
    poster_path: "/yvirUYrva23IudARHn3mMGVxWqM.jpg",
    release_date: "2025-07-29",
    title: "War of the Worlds",
    video: false,
    vote_average: 4.373,
    vote_count: 267,
  },
  {
    adult: false,
    backdrop_path: "/fncHijpWjitFBmj7SX5z148XEhP.jpg",
    genre_ids: [878, 12, 28],
    id: 1234821,
    original_language: "en",
    original_title: "Jurassic World Rebirth",
    overview:
      "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
    popularity: 1127.7172,
    poster_path: "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
    release_date: "2025-07-01",
    title: "Jurassic World Rebirth",
    video: false,
    vote_average: 6.412,
    vote_count: 1376,
  },
  {
    adult: false,
    backdrop_path: "/y7tjLYcq2ZGy2DNG0ODhGX9Tm60.jpg",
    genre_ids: [28, 35, 80],
    id: 1106289,
    original_language: "en",
    original_title: "The Pickup",
    overview:
      "A routine cash pickup takes a wild turn when mismatched armored truck drivers Russell and Travis are ambushed by ruthless criminals led by savvy mastermind Zoe.",
    popularity: 517.1636,
    poster_path: "/vFWvWhfAvij8UIngg2Vf6JV95Cr.jpg",
    release_date: "2025-07-27",
    title: "The Pickup",
    video: false,
    vote_average: 6.613,
    vote_count: 177,
  },
  {
    adult: false,
    backdrop_path: "/yujcZMkNKtNXPvRGyTA3e3VCrbx.jpg",
    genre_ids: [28, 14, 10752],
    id: 1155281,
    original_language: "zh",
    original_title: "封神第二部：战火西岐",
    overview:
      "Taishi Wen Zhong led the army of Shang Dynasty including Deng Chanyu and four generals of the Mo Family to Xiqi. With the help of Kunlun immortals such as Jiang Ziya, Ji Fa led the army and civilians of Xiqi to defend their homeland.",
    popularity: 491.2509,
    poster_path: "/dfUCs5HNtGu4fofh83uiE2Qcy3v.jpg",
    release_date: "2025-01-29",
    title: "Creation of the Gods II: Demon Force",
    video: false,
    vote_average: 6.282,
    vote_count: 71,
  },
  {
    adult: false,
    backdrop_path: "/bP6BqIljp4a3BqhxN7YPckcpKI.jpg",
    genre_ids: [28, 18, 36],
    id: 1195631,
    original_language: "en",
    original_title: "William Tell",
    overview:
      "The narrative unfolds in the 14th Century, when the European nations vie for supremacy within the Holy Roman Empire. The ambitious Austrian Empire, desiring more land, invades neighbouring Switzerland, a serene and pastoral nation. Protagonist William Tell, a formerly peaceful hunter, finds himself forced to take action as his family and homeland come under threat from the oppressive Austrian King and his ruthless warlords.",
    popularity: 468.2674,
    poster_path: "/8SdaetXSTPyQVDb5pTEPRLBSx15.jpg",
    release_date: "2025-01-17",
    title: "William Tell",
    video: false,
    vote_average: 6.327,
    vote_count: 84,
  },
  {
    adult: false,
    backdrop_path: "/iZztGzckOMByRRQgsFh2yk3udkU.jpg",
    genre_ids: [28, 27, 10749],
    id: 986206,
    original_language: "en",
    original_title: "Night Carnage",
    overview:
      "A blogger who is also a werewolf meets a dashing playboy with a dark secret of his own. Starring Logan Andrews and Christian Howard.",
    popularity: 327.6566,
    poster_path: "/w0wjPQKhlqisSbylf1sWZiNyc2h.jpg",
    release_date: "2025-07-29",
    title: "Night Carnage",
    video: false,
    vote_average: 5.842,
    vote_count: 38,
  },
  {
    adult: false,
    backdrop_path: "/AeDzjt00Hfh9CuW7TIUdYBJmWYM.jpg",
    genre_ids: [14, 10751, 28, 12],
    id: 1087192,
    original_language: "en",
    original_title: "How to Train Your Dragon",
    overview:
      "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
    popularity: 395.2745,
    poster_path: "/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg",
    release_date: "2025-06-06",
    title: "How to Train Your Dragon",
    video: false,
    vote_average: 8.023,
    vote_count: 1536,
  },
  {
    adult: false,
    backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
    genre_ids: [16, 28, 14, 53],
    id: 1311031,
    original_language: "ja",
    original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
    overview:
      "As the Demon Slayer Corps members and Hashira engaged in a group strength training program, the Hashira Training, in preparation for the forthcoming battle against the demons, Muzan Kibutsuji appears at the Ubuyashiki Mansion. With the head of the Demon Corps in danger, Tanjiro and the Hashira rush to the headquarters but are plunged into a deep descent to a mysterious space by the hands of Muzan Kibutsuji.  The destination of where Tanjiro and Demon Slayer Corps have fallen is the demons' stronghold – the Infinity Castle. And so, the battleground is set as the final battle between the Demon Slayer Corps and the demons ignites.",
    popularity: 352.5289,
    poster_path: "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
    release_date: "2025-07-18",
    title: "Demon Slayer: Kimetsu no Yaiba — Infinity Castle",
    video: false,
    vote_average: 7.2,
    vote_count: 68,
  },
  {
    adult: false,
    backdrop_path: "/7A3ru3bxmWtyF0ep0CJcLLzWT35.jpg",
    genre_ids: [28, 18, 36],
    id: 1185528,
    original_language: "zh",
    original_title: "射雕英雄传：侠之大者",
    overview:
      "Under Genghis Khan, the Mongolian army pushes west to destroy the Jin Dynasty, setting its sights on the Song Dynasty next. Amid internal conflicts among martial arts schools, Guo Jing unites the Central Plains' warriors to defend Xiangyang, embodying courage and loyalty in the fight for the nation.",
    popularity: 388.8982,
    poster_path: "/fUCFEGFlMIFet9ja72JDAeG1he8.jpg",
    release_date: "2025-01-29",
    title: "Legends of the Condor Heroes: The Gallants",
    video: false,
    vote_average: 6.152,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: "/c9xmB53umjnrCMS4pZz11clF3yJ.jpg",
    genre_ids: [16, 14, 12, 28],
    id: 980477,
    original_language: "zh",
    original_title: "哪吒之魔童闹海",
    overview:
      "After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.",
    popularity: 274.277,
    poster_path: "/293Mo4GWf7Tl0TfAr5NFghqeMy7.jpg",
    release_date: "2025-01-29",
    title: "Ne Zha 2",
    video: false,
    vote_average: 8.035,
    vote_count: 260,
  },
  {
    adult: false,
    backdrop_path: "/zav0v7gLWMu6pVwgsIAwt11GJ4C.jpg",
    genre_ids: [27, 53, 878],
    id: 1100988,
    original_language: "en",
    original_title: "28 Years Later",
    overview:
      "Twenty-eight years since the rage virus escaped a biological weapons laboratory, now, still in a ruthlessly enforced quarantine, some have found ways to exist amidst the infected. One such group lives on a small island connected to the mainland by a single, heavily-defended causeway. When one member departs on a mission into the dark heart of the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors as well.",
    popularity: 254.6574,
    poster_path: "/mIg1qCkVxnAlM2TK3RUF0tdEXlE.jpg",
    release_date: "2025-06-18",
    title: "28 Years Later",
    video: false,
    vote_average: 6.874,
    vote_count: 1047,
  },
  {
    adult: false,
    backdrop_path: "/cEQMqB3ahd4mfeUN6VGC0ouVnZZ.jpg",
    genre_ids: [28, 878, 53],
    id: 1071585,
    original_language: "en",
    original_title: "M3GAN 2.0",
    overview:
      "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
    popularity: 240.5492,
    poster_path: "/4a63rQqIDTrYNdcnTXdPsQyxVLo.jpg",
    release_date: "2025-06-25",
    title: "M3GAN 2.0",
    video: false,
    vote_average: 7.606,
    vote_count: 661,
  },
  {
    adult: false,
    backdrop_path: "/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
    genre_ids: [10751, 878, 35, 12],
    id: 552524,
    original_language: "en",
    original_title: "Lilo & Stitch",
    overview:
      "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
    popularity: 242.3687,
    poster_path: "/tUae3mefrDVTgm5mRzqWnZK6fOP.jpg",
    release_date: "2025-05-17",
    title: "Lilo & Stitch",
    video: false,
    vote_average: 7.323,
    vote_count: 1299,
  },
  {
    adult: false,
    backdrop_path: "/A466i5iATrpbVjX30clP1Zyfp31.jpg",
    genre_ids: [10749, 35, 18],
    id: 1307078,
    original_language: "en",
    original_title: "My Oxford Year",
    overview:
      "An ambitious American fulfilling her dream of studying at Oxford falls for a charming Brit hiding a secret that may upend her perfectly planned life.",
    popularity: 236.4227,
    poster_path: "/jrhXbIOFingzdLjkccjg9vZnqIp.jpg",
    release_date: "2025-07-31",
    title: "My Oxford Year",
    video: false,
    vote_average: 7.244,
    vote_count: 211,
  },
  {
    adult: false,
    backdrop_path: "/kyqM6padQzZ1eYxv84i9smNvZAG.jpg",
    genre_ids: [27, 9648],
    id: 1078605,
    original_language: "en",
    original_title: "Weapons",
    overview:
      "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
    popularity: 249.1853,
    poster_path: "/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg",
    release_date: "2025-08-06",
    title: "Weapons",
    video: false,
    vote_average: 7.8,
    vote_count: 200,
  },
  {
    adult: false,
    backdrop_path: "/eU7IfdWq8KQy0oNd4kKXS0QUR08.jpg",
    genre_ids: [878, 12, 28],
    id: 1061474,
    original_language: "en",
    original_title: "Superman",
    overview:
      "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
    popularity: 199.5313,
    poster_path: "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
    release_date: "2025-07-09",
    title: "Superman",
    video: false,
    vote_average: 7.679,
    vote_count: 1640,
  },
  {
    adult: false,
    backdrop_path: "/s94NjfKkcSczZ1FembwmQZwsuwY.jpg",
    genre_ids: [878, 12],
    id: 617126,
    original_language: "en",
    original_title: "The Fantastic 4: First Steps",
    overview:
      "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
    popularity: 192.4302,
    poster_path: "/x26MtUlwtWD26d0G0FXcppxCJio.jpg",
    release_date: "2025-07-23",
    title: "The Fantastic 4: First Steps",
    video: false,
    vote_average: 7.26,
    vote_count: 915,
  },
  {
    adult: false,
    backdrop_path: "/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg",
    genre_ids: [28, 12, 18],
    id: 1011477,
    original_language: "en",
    original_title: "Karate Kid: Legends",
    overview:
      "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
    popularity: 195.2787,
    poster_path: "/AEgggzRr1vZCLY86MAp93li43z.jpg",
    release_date: "2025-05-08",
    title: "Karate Kid: Legends",
    video: false,
    vote_average: 7.162,
    vote_count: 638,
  },
  {
    adult: false,
    backdrop_path: "/wFzI8o0jEMYfNugglP4wjFIr647.jpg",
    genre_ids: [28, 53, 80],
    id: 715253,
    original_language: "ko",
    original_title: "유령",
    overview:
      'In 1933, when Korea was under Japanese occupation, five people in Gyeongseong are suspected to be "Phantom" spies of the anti-Japanese organization.',
    popularity: 169.7898,
    poster_path: "/n1rxZ4wovf7BYhLNwCqde8I3I2N.jpg",
    release_date: "2023-01-18",
    title: "Phantom",
    video: false,
    vote_average: 6.914,
    vote_count: 58,
  },
  {
    adult: false,
    backdrop_path: "/962KXsr09uK8wrmUg9TjzmE7c4e.jpg",
    genre_ids: [28, 53, 18],
    id: 1119878,
    original_language: "en",
    original_title: "Ice Road: Vengeance",
    overview:
      "Big rig ice road driver Mike McCann travels to Nepal to scatter his late brother’s ashes on Mt. Everest. While on a packed tour bus traversing the deadly 12,000 ft. terrain of the infamous Road to the Sky, McCann and his mountain guide encounter a group of mercenaries and must fight to save themselves, the busload of innocent travelers, and the local villagers’ homeland.",
    popularity: 179.2397,
    poster_path: "/cQN9rZj06rXMVkk76UF1DfBAico.jpg",
    release_date: "2025-06-27",
    title: "Ice Road: Vengeance",
    video: false,
    vote_average: 6.861,
    vote_count: 162,
  },
];
export const fallbackTopRatedMovies = [
  {
    adult: false,
    backdrop_path: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 30.1019,
    poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.712,
    vote_count: 28670,
  },
  {
    adult: false,
    backdrop_path: "/htuuuEwAvDVECMpb0ltLLyZyDDt.jpg",
    genre_ids: [18, 80],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 27.6438,
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.686,
    vote_count: 21699,
  },
  {
    adult: false,
    backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    genre_ids: [18, 80],
    id: 240,
    original_language: "en",
    original_title: "The Godfather Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 15.8254,
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    title: "The Godfather Part II",
    video: false,
    vote_average: 8.571,
    vote_count: 13098,
  },
  {
    adult: false,
    backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 13.6979,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    video: false,
    vote_average: 8.566,
    vote_count: 16613,
  },
  {
    adult: false,
    backdrop_path: "/bxgTSUenZDHNFerQ1whRKplrMKF.jpg",
    genre_ids: [18],
    id: 389,
    original_language: "en",
    original_title: "12 Angry Men",
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    popularity: 15.2506,
    poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    release_date: "1957-04-10",
    title: "12 Angry Men",
    video: false,
    vote_average: 8.549,
    vote_count: 9306,
  },
  {
    adult: false,
    backdrop_path: "/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg",
    genre_ids: [16, 10751, 14],
    id: 129,
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    popularity: 17.9329,
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    video: false,
    vote_average: 8.5,
    vote_count: 17351,
  },
  {
    adult: false,
    backdrop_path: "/enNubozHn9pXi0ycTVYUWfpHZm.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 24.6329,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.523,
    vote_count: 34196,
  },
  {
    adult: false,
    backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 5.8678,
    poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.517,
    vote_count: 4500,
  },
  {
    adult: false,
    backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
    genre_ids: [14, 18, 80],
    id: 497,
    original_language: "en",
    original_title: "The Green Mile",
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    popularity: 17.1823,
    poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    video: false,
    vote_average: 8.503,
    vote_count: 18269,
  },
  {
    adult: false,
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    genre_ids: [35, 53, 18],
    id: 496243,
    original_language: "ko",
    original_title: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    popularity: 17.2195,
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    title: "Parasite",
    video: false,
    vote_average: 8.5,
    vote_count: 19339,
  },
  {
    adult: false,
    backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    genre_ids: [12, 14, 28],
    id: 122,
    original_language: "en",
    original_title: "The Lord of the Rings: The Return of the King",
    overview:
      "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
    popularity: 18.1638,
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-17",
    title: "The Lord of the Rings: The Return of the King",
    video: false,
    vote_average: 8.489,
    vote_count: 25324,
  },
  {
    adult: false,
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80, 35, 18],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 16.3553,
    poster_path: "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    video: false,
    vote_average: 8.487,
    vote_count: 28947,
  },
  {
    adult: false,
    backdrop_path: "/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg",
    genre_ids: [16, 10749, 18],
    id: 372058,
    original_language: "ja",
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    popularity: 12.1679,
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    video: false,
    vote_average: 8.481,
    vote_count: 11906,
  },
  {
    adult: false,
    backdrop_path: "/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    popularity: 17.5194,
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.467,
    vote_count: 28490,
  },
  {
    adult: false,
    backdrop_path: "/x4biAVdPVCghBlsVIzB6NmbghIz.jpg",
    genre_ids: [37],
    id: 429,
    original_language: "it",
    original_title: "Il buono, il brutto, il cattivo",
    overview:
      "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    popularity: 10.638,
    poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    release_date: "1966-12-22",
    title: "The Good, the Bad and the Ugly",
    video: false,
    vote_average: 8.466,
    vote_count: 9107,
  },
  {
    adult: false,
    backdrop_path: "/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg",
    genre_ids: [12, 18, 878],
    id: 157336,
    original_language: "en",
    original_title: "Interstellar",
    overview:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    popularity: 40.605,
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    release_date: "2014-11-05",
    title: "Interstellar",
    video: false,
    vote_average: 8.458,
    vote_count: 37612,
  },
  {
    adult: false,
    backdrop_path: "/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg",
    genre_ids: [28, 18],
    id: 346,
    original_language: "ja",
    original_title: "七人の侍",
    overview:
      "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
    popularity: 6.1932,
    poster_path: "/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg",
    release_date: "1954-04-26",
    title: "Seven Samurai",
    video: false,
    vote_average: 8.456,
    vote_count: 3959,
  },
  {
    adult: false,
    backdrop_path: "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
    genre_ids: [18, 80],
    id: 769,
    original_language: "en",
    original_title: "GoodFellas",
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    popularity: 12.9568,
    poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    release_date: "1990-09-12",
    title: "GoodFellas",
    video: false,
    vote_average: 8.455,
    vote_count: 13529,
  },
  {
    adult: false,
    backdrop_path: "/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg",
    genre_ids: [16, 18, 10752],
    id: 12477,
    original_language: "ja",
    original_title: "火垂るの墓",
    overview:
      "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
    popularity: 0.0104,
    poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
    release_date: "1988-04-16",
    title: "Grave of the Fireflies",
    video: false,
    vote_average: 8.4,
    vote_count: 5998,
  },
  {
    adult: false,
    backdrop_path: "/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg",
    genre_ids: [35, 18],
    id: 637,
    original_language: "it",
    original_title: "La vita è bella",
    overview:
      "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    popularity: 7.8493,
    poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    release_date: "1997-12-20",
    title: "Life Is Beautiful",
    video: false,
    vote_average: 8.443,
    vote_count: 13474,
  },
];

export const fallbackUpcomingMovies = [
  {
    adult: false,
    backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
    genre_ids: [16, 28, 14, 53],
    id: 1311031,
    original_language: "ja",
    original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
    overview:
      "As the Demon Slayer Corps members and Hashira engaged in a group strength training program, the Hashira Training, in preparation for the forthcoming battle against the demons, Muzan Kibutsuji appears at the Ubuyashiki Mansion. With the head of the Demon Corps in danger, Tanjiro and the Hashira rush to the headquarters but are plunged into a deep descent to a mysterious space by the hands of Muzan Kibutsuji.  The destination of where Tanjiro and Demon Slayer Corps have fallen is the demons' stronghold – the Infinity Castle. And so, the battleground is set as the final battle between the Demon Slayer Corps and the demons ignites.",
    popularity: 352.5289,
    poster_path: "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
    release_date: "2025-07-18",
    title: "Demon Slayer: Kimetsu no Yaiba — Infinity Castle",
    video: false,
    vote_average: 7.1,
    vote_count: 68,
  },
  {
    adult: false,
    backdrop_path: "/c9xmB53umjnrCMS4pZz11clF3yJ.jpg",
    genre_ids: [16, 14, 12, 28],
    id: 980477,
    original_language: "zh",
    original_title: "哪吒之魔童闹海",
    overview:
      "After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.",
    popularity: 274.277,
    poster_path: "/293Mo4GWf7Tl0TfAr5NFghqeMy7.jpg",
    release_date: "2025-01-29",
    title: "Ne Zha 2",
    video: false,
    vote_average: 8.019,
    vote_count: 258,
  },
  {
    adult: false,
    backdrop_path: "/kyqM6padQzZ1eYxv84i9smNvZAG.jpg",
    genre_ids: [27, 9648],
    id: 1078605,
    original_language: "en",
    original_title: "Weapons",
    overview:
      "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
    popularity: 249.1853,
    poster_path: "/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg",
    release_date: "2025-08-06",
    title: "Weapons",
    video: false,
    vote_average: 7.715,
    vote_count: 200,
  },
  {
    adult: false,
    backdrop_path: "/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg",
    genre_ids: [28, 12, 18],
    id: 1011477,
    original_language: "en",
    original_title: "Karate Kid: Legends",
    overview:
      "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
    popularity: 195.2787,
    poster_path: "/AEgggzRr1vZCLY86MAp93li43z.jpg",
    release_date: "2025-05-08",
    title: "Karate Kid: Legends",
    video: false,
    vote_average: 7.16,
    vote_count: 636,
  },
  {
    adult: false,
    backdrop_path: "/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg",
    genre_ids: [16, 14, 35, 10402, 10751],
    id: 803796,
    original_language: "en",
    original_title: "KPop Demon Hunters",
    overview:
      "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
    popularity: 157.9966,
    poster_path: "/22AouvwlhlXbe3nrFcjzL24bvWH.jpg",
    release_date: "2025-06-20",
    title: "KPop Demon Hunters",
    video: false,
    vote_average: 8.426,
    vote_count: 962,
  },
  {
    adult: false,
    backdrop_path: "/oPgXVSdGR9dGwbmvIToOCMmsdc2.jpg",
    genre_ids: [28, 53, 80],
    id: 541671,
    original_language: "en",
    original_title: "Ballerina",
    overview:
      "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
    popularity: 158.5197,
    poster_path: "/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
    release_date: "2025-06-04",
    title: "Ballerina",
    video: false,
    vote_average: 7.437,
    vote_count: 1295,
  },
  {
    adult: false,
    backdrop_path: "/2DcD4Hh80SW7YVpwckkiEFRZX06.jpg",
    genre_ids: [28, 35],
    id: 1124619,
    original_language: "en",
    original_title: "Bride Hard",
    overview:
      "Sam is a secret agent whose toughest mission to date is pleasing her bride-to-be best friend at a lavish destination wedding. When a team of mercenaries crashes the party and takes the guests hostage, Sam is thrown into a fight unlike any before — one where she can’t risk blowing her cover or ruining the big day. As she takes on the bad guys in a high-stakes battle disguised as a fairy-tale affair, she realizes the real threat might be closer than she thinks.",
    popularity: 130.5087,
    poster_path: "/3mExdWLSxAiUCb4NMcYmxSkO7n4.jpg",
    release_date: "2025-06-19",
    title: "Bride Hard",
    video: false,
    vote_average: 5.746,
    vote_count: 69,
  },
  {
    adult: false,
    backdrop_path: "/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg",
    genre_ids: [27, 9648],
    id: 574475,
    original_language: "en",
    original_title: "Final Destination Bloodlines",
    overview:
      "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
    popularity: 125.8909,
    poster_path: "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
    release_date: "2025-05-14",
    title: "Final Destination Bloodlines",
    video: false,
    vote_average: 7.176,
    vote_count: 1900,
  },
  {
    adult: false,
    backdrop_path: "/jvpkBenB6hv19WWYVlaiow8zklq.jpg",
    genre_ids: [10751, 35, 80, 12, 16],
    id: 1175942,
    original_language: "en",
    original_title: "The Bad Guys 2",
    overview:
      "The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.",
    popularity: 92.8608,
    poster_path: "/26oSPnq0ct59l07QOXZKyzsiRtN.jpg",
    release_date: "2025-07-24",
    title: "The Bad Guys 2",
    video: false,
    vote_average: 7.6,
    vote_count: 52,
  },
  {
    adult: false,
    backdrop_path: "/u2ctOiURF9hL3hmXmEMHxcVPVrQ.jpg",
    genre_ids: [27],
    id: 1242011,
    original_language: "en",
    original_title: "Together",
    overview:
      "With a move to the countryside already testing the limits of a couple's relationship, a supernatural encounter begins an extreme transformation of their love, their lives, and their flesh.",
    popularity: 82.7075,
    poster_path: "/inliWt3ukcpKDGPpEe2lRDLwK2r.jpg",
    release_date: "2025-07-28",
    title: "Together",
    video: false,
    vote_average: 7.391,
    vote_count: 128,
  },
  {
    adult: false,
    backdrop_path: "/2IIKts2A9vnUdM9tTC76B8tDmuZ.jpg",
    genre_ids: [27],
    id: 1151031,
    original_language: "en",
    original_title: "Bring Her Back",
    overview:
      "Following the death of their father, a brother and sister are introduced to their new sibling by their foster mother, only to learn that she has a terrifying secret.",
    popularity: 80.0815,
    poster_path: "/tObSf1VzzHt9xB0csanFtb3DRjf.jpg",
    release_date: "2025-05-28",
    title: "Bring Her Back",
    video: false,
    vote_average: 7.428,
    vote_count: 492,
  },
  {
    adult: false,
    backdrop_path: "/dv5Iu1cI6nsxyPfFusEYbeRkrIJ.jpg",
    genre_ids: [35, 80],
    id: 1035259,
    original_language: "en",
    original_title: "The Naked Gun",
    overview:
      "Only one man has the particular set of skills... to lead Police Squad and save the world: Lt. Frank Drebin Jr.",
    popularity: 67.2147,
    poster_path: "/rmwQ8GsdQ1M3LtemNWLErle2nBU.jpg",
    release_date: "2025-07-30",
    title: "The Naked Gun",
    video: false,
    vote_average: 6.99,
    vote_count: 144,
  },
  {
    adult: false,
    backdrop_path: "/lqwwGkwJHtz9QgKtz4zeY19YgDg.jpg",
    genre_ids: [10749, 18],
    id: 1136867,
    original_language: "en",
    original_title: "Materialists",
    overview:
      "A young, ambitious New York City matchmaker finds herself torn between the perfect match and her imperfect ex.",
    popularity: 65.8283,
    poster_path: "/eDo0pNruy0Qgj6BdTyHIR4cxHY8.jpg",
    release_date: "2025-06-12",
    title: "Materialists",
    video: false,
    vote_average: 6.736,
    vote_count: 296,
  },
  {
    adult: false,
    backdrop_path: "/yAqL0makiGke5yYiVWpmBDSKIVP.jpg",
    genre_ids: [27, 18, 53],
    id: 1278950,
    original_language: "en",
    original_title: "The Ritual",
    overview:
      "Two priests, one in crisis with his faith and the other confronting a turbulent past, must overcome their differences to perform a risky exorcism.",
    popularity: 64.8585,
    poster_path: "/ktqPs5QyuF8SpKnipvVHb3fwD8d.jpg",
    release_date: "2025-04-18",
    title: "The Ritual",
    video: false,
    vote_average: 5.787,
    vote_count: 134,
  },
  {
    adult: false,
    backdrop_path: "/eNSUknQqzTXWE5EeT8ZnVccEPR0.jpg",
    genre_ids: [27, 53],
    id: 1285965,
    original_language: "en",
    original_title: "Dangerous Animals",
    overview:
      "A savvy and free-spirited surfer is abducted by a shark-obsessed serial killer. Held captive on his boat, she must figure out how to escape before he carries out a ritualistic feeding to the sharks below.",
    popularity: 62.1327,
    poster_path: "/9tk3Si960hg4E49eMt81dS7Qe9Z.jpg",
    release_date: "2025-06-05",
    title: "Dangerous Animals",
    video: false,
    vote_average: 6.476,
    vote_count: 143,
  },
  {
    adult: false,
    backdrop_path: "/dcLV5rEXuQRW0ZlB7IMLArHMyWh.jpg",
    genre_ids: [14, 35, 10751],
    id: 1125257,
    original_language: "en",
    original_title: "Freakier Friday",
    overview:
      "Years after Tess and Anna endured an identity crisis, Anna now has a daughter of her own and a soon-to-be stepdaughter. As they navigate the myriad challenges that come when two families merge, Tess and Anna discover lightning might indeed strike twice.",
    popularity: 86.0138,
    poster_path: "/9wV65OmsjLAqBfDnYTkMPutXH8j.jpg",
    release_date: "2025-08-06",
    title: "Freakier Friday",
    video: false,
    vote_average: 7.3,
    vote_count: 41,
  },
  {
    adult: false,
    backdrop_path: "/9fmqG3uyDZ8n1I3elp5URVgQMbz.jpg",
    genre_ids: [18, 35],
    id: 1205515,
    original_language: "en",
    original_title: "Sorry, Baby",
    overview:
      "Something bad happened to Agnes. But life goes on… for everyone around her, at least.",
    popularity: 45.7841,
    poster_path: "/iq1QtN1H8AVEBfl1SgNAqhMgTbQ.jpg",
    release_date: "2025-06-27",
    title: "Sorry, Baby",
    video: false,
    vote_average: 6.58,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: "/uUFxsPRaeRnZccvMz6SCZ1FK6ha.jpg",
    genre_ids: [878, 18, 53],
    id: 1280444,
    original_language: "en",
    original_title: "The Occupant",
    overview:
      "Desperate to save her sister, Abby takes a dangerous job in the remote Georgian wilderness. Stranded in the mountains after her helicopter crashes, she finds hope through John, a mysterious helper radioing from nearby. As he guides her through the harsh conditions, Abby struggles to survive, and her grip on reality falters until she is faced with an impossible choice.",
    popularity: 40.8998,
    poster_path: "/aRWeT2UIkaWolqQ6fYeHOB1D6vA.jpg",
    release_date: "2025-08-07",
    title: "The Occupant",
    video: false,
    vote_average: 6.444,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: "/yiyy3ZtyuGjNs81kVV3cC4mTWgA.jpg",
    genre_ids: [27, 9648, 53],
    id: 713364,
    original_language: "en",
    original_title: "Clown in a Cornfield",
    overview:
      "Quinn and her father have just moved to the quiet town of Kettle Springs hoping for a fresh start. Instead, she discovers a fractured community that has fallen on hard times after the treasured Baypen Corn Syrup Factory burned down. As the locals bicker amongst themselves and tensions boil over, a sinister, grinning figure emerges from the cornfields to cleanse the town of its burdens, one bloody victim at a time.",
    popularity: 43.397,
    poster_path: "/bghFYMUMEKK6GyTHRA7XVC8uWn6.jpg",
    release_date: "2025-05-08",
    title: "Clown in a Cornfield",
    video: false,
    vote_average: 6.285,
    vote_count: 219,
  },
  {
    adult: false,
    backdrop_path: "/hJXsJkQC8F3bgUTfsD402uj2Ewf.jpg",
    genre_ids: [16, 12, 10751],
    id: 666154,
    original_language: "en",
    original_title: "Kayara",
    overview:
      "A courageous and athletic teenager, Kayara dreams that she is destined to be the first female to break into the league of Chasquis - the official messengers of the Incan empire. As she learns what it takes to be a Chasqui along with its challenges, she tackles every mission she gets and discovers the ancient stories of her land and her people.",
    popularity: 29.7951,
    poster_path: "/tpZdjnoJ6Z3NsSxI6HjAIggrcEv.jpg",
    release_date: "2025-01-02",
    title: "Kayara",
    video: false,
    vote_average: 7.595,
    vote_count: 95,
  },
];

export const fallbackTrailerKeys = {
  541671: "LSW0hihUzxU",
  617126: "GXQRuee6r34",
  755898: "d9erkpdh5o0",
  986206: "QgT_a2ilPMQ",
  1011477: "ZuKbmha4QpA",
  1061474: "xFU8U4UVUBs",
  1071585: "dhcVNL1YPdY",
  1078605: "Vu1H6WHPikQ",
  1100988: "kLSJMVzmucU",
  1106289: "g-y-5OT8uYo",
  1124619: "arjGaz3Gg7c",
  1181540: "em64F7k27ws",
  1185528: "EyF3nbkaSX0",
  1195631: "-FkkyicYgzE",
  1225572: "NvCSdapsDss",
  1234821: "Af0opnvHeak",
  1263256: "qd4UhBpg3kM",
  1307078: "oxVtspc8whk",
  1311031: "VCC958XvXpA",
  1452176: "-2BJrCzvEZQ",
  default: "dQw4w9WgXcQ",
};

export const GENRE_ID_MAP = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Documentary",
  18: "Drama",
  10751: "Family",
  14: "Fantasy",
  36: "History",
  27: "Horror",
  10402: "Music",
  9648: "Mystery",
  10749: "Romance",
  878: "Science Fiction",
  10770: "TV Movie",
  53: "Thriller",
  10752: "War",
  37: "Western",
};
